# Generated by Django 2.0.4 on 2018-05-24 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=10, unique=True)),
                ('nama_produk', models.CharField(max_length=100)),
                ('nominal', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('parse_text', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nominal'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.CharField(blank=True, max_length=30)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('productcode', models.CharField(blank=True, max_length=30)),
                ('trxtime', models.CharField(blank=True, max_length=50)),
                ('accno', models.CharField(blank=True, max_length=50)),
                ('nohp', models.CharField(blank=True, max_length=50)),
                ('accname', models.CharField(blank=True, max_length=200)),
                ('billperiode', models.CharField(blank=True, max_length=50)),
                ('serialno', models.CharField(blank=True, max_length=200)),
                ('nominal', models.IntegerField(default=0)),
                ('adminfee', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('url_struk', models.CharField(blank=True, max_length=200)),
                ('refca', models.CharField(blank=True, max_length=100)),
                ('refsb', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_code', models.CharField(blank=True, max_length=16)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('account_num', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Success'), (1, 'Pending'), (9, 'Gagal')], default=0)),
                ('request_type', models.CharField(choices=[('i', 'INQUIRY'), ('p', 'PAY')], default='i', max_length=1)),
                ('struk', models.TextField(blank=True, max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('pembukuan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bukupln', to='userprofile.PembukuanTransaksi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epln.Product')),
                ('ref_sb_trx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epln.Transaksi')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userpln', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddField(
            model_name='responsetransaksi',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epln.Transaksi'),
        ),
    ]
