# Generated by Django 2.0.4 on 2018-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='account_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
