# Generated by Django 2.0.4 on 2018-05-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0002_transaksi_account_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='pembukuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bukupln', to='userprofile.PembukuanTransaksi'),
        ),
    ]
