# Generated by Django 2.0.4 on 2018-07-01 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20180630_1244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epln', '0002_transaksi_catatan_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTransaksiRb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(blank=True, max_length=20)),
                ('waktu', models.CharField(blank=True, max_length=40)),
                ('idpel1', models.CharField(blank=True, max_length=20)),
                ('idpel2', models.CharField(blank=True, max_length=20)),
                ('idpel3', models.CharField(blank=True, max_length=20)),
                ('nama_pelanggan', models.CharField(blank=True, max_length=200)),
                ('periode', models.CharField(blank=True, max_length=40)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('admin', models.PositiveIntegerField(default=0)),
                ('ref1', models.CharField(blank=True, max_length=100)),
                ('ref2', models.CharField(blank=True, max_length=100)),
                ('ref3', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('ket', models.CharField(blank=True, max_length=100)),
                ('saldo_terpotong', models.PositiveIntegerField(default=0)),
                ('sisa_saldo', models.PositiveIntegerField(default=0)),
                ('url_struk', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField(blank=True, max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiRb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_code', models.CharField(blank=True, max_length=16)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('idpel', models.CharField(blank=True, max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Success'), (1, 'Pending'), (9, 'Gagal')], default=0)),
                ('request_type', models.CharField(choices=[('i', 'INQUIRY'), ('p', 'PAY')], default='i', max_length=1)),
                ('struk', models.TextField(blank=True, max_length=2000)),
                ('ref1', models.CharField(blank=True, max_length=16)),
                ('ref2', models.CharField(blank=True, max_length=16)),
                ('ref3', models.CharField(blank=True, max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('catatan_modal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epln_rbcctt_modal', to='userprofile.CatatanModal')),
                ('pembukuan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epln_rbbuku_transaksi', to='userprofile.PembukuanTransaksi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epln.Product')),
                ('ref_inquery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epln.TransaksiRb')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epln_rbuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddField(
            model_name='responsetransaksirb',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epln.TransaksiRb'),
        ),
    ]
