# Generated by Django 2.0.4 on 2018-05-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0003_auto_20180517_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetransaksi',
            name='serialno',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
