# Generated by Django 2.0.4 on 2018-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0003_auto_20180701_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksirb',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
