# Generated by Django 2.0.4 on 2018-05-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0004_responsetransaksi_serialno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetransaksi',
            name='refsbinq',
        ),
    ]
