# Generated by Django 2.0.4 on 2018-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0005_remove_responsetransaksi_refsbinq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
