# Generated by Django 2.0.4 on 2018-05-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epln', '0006_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='struk',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
