# Generated by Django 2.0.4 on 2018-05-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=3, unique=True)),
                ('operator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrefixNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4, unique=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpulsa.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_internal', models.CharField(blank=True, max_length=10)),
                ('nominal', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('kode_external', models.CharField(max_length=15)),
                ('price_beli', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpulsa.Operator')),
            ],
        ),
    ]
