# Generated by Django 2.0.4 on 2018-06-03 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0007_auto_20180601_1514'),
        ('mpulsa', '0002_transaksi_catatan_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('biller', models.CharField(choices=[('SB', 'Siap Bayar'), ('RB', 'Raja Biller')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTransaksiRb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=30)),
                ('waktu', models.CharField(max_length=40)),
                ('no_hp', models.CharField(max_length=20)),
                ('sn', models.CharField(max_length=100)),
                ('ref1', models.CharField(max_length=100)),
                ('ref2', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('ket', models.CharField(blank=True, max_length=200)),
                ('saldo_terpotong', models.IntegerField(default=0)),
                ('sisa_saldo', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiRb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_code', models.CharField(blank=True, max_length=16)),
                ('price', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Success'), (1, 'Pending'), (9, 'Gagal')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('catatan_modal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulsa_rbcctt_modal', to='userprofile.CatatanModal')),
                ('pembukuan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpulsa_rbbuku_transaksi', to='userprofile.PembukuanTransaksi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpulsa.Product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='biller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpulsa.Biller'),
        ),
    ]
