# Generated by Django 2.0.4 on 2018-05-02 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0002_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
