# Generated by Django 2.0.4 on 2018-06-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0003_auto_20180603_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetransaksirb',
            name='trx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpulsa.TransaksiRb'),
        ),
        migrations.AlterField(
            model_name='transaksirb',
            name='catatan_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpulsa_rbcctt_modal', to='userprofile.CatatanModal'),
        ),
    ]
