# Generated by Django 2.0.4 on 2018-05-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0003_auto_20180502_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
