# Generated by Django 2.0.4 on 2018-06-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0004_auto_20180604_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetransaksirb',
            name='trx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpulsa.TransaksiRb'),
        ),
        migrations.AlterField(
            model_name='transaksirb',
            name='pembukuan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpulsa_rbbuku_transaksi', to='userprofile.PembukuanTransaksi'),
        ),
    ]
