# Generated by Django 2.0.4 on 2018-05-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180502_1307'),
        ('mpulsa', '0004_auto_20180502_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='pembukuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.PembukuanTransaksi'),
        ),
    ]
