# Generated by Django 2.0.4 on 2018-05-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0005_transaksi_pembukuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(blank=True, max_length=200)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=20)),
                ('trxtime', models.CharField(blank=True, max_length=50)),
                ('nohp', models.CharField(max_length=30)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('refca', models.CharField(blank=True, max_length=50)),
                ('refsb', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('trx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpulsa.Transaksi')),
            ],
        ),
    ]
