# Generated by Django 2.0.4 on 2018-05-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0006_responsetransaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetransaksi',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mpulsa.Transaksi'),
        ),
    ]
