# Generated by Django 2.0.4 on 2018-06-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0006_auto_20180607_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['operator', '-type_layanan', 'nominal']},
        ),
    ]
