# Generated by Django 2.0.4 on 2018-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0008_auto_20180504_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetransaksi',
            name='nohp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
