# Generated by Django 2.0.4 on 2018-05-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0009_auto_20180507_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
