# Generated by Django 2.0.4 on 2018-05-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0010_product_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['operator', 'nominal']},
        ),
    ]
