# Generated by Django 2.0.4 on 2018-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0011_auto_20180509_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='type_layanan',
            field=models.CharField(choices=[('D', 'DATA'), ('P', 'PULSA')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='parse_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operator',
            name='kode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kode_internal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
