# Generated by Django 2.0.4 on 2018-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0012_auto_20180516_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='type_layanan',
        ),
        migrations.AddField(
            model_name='product',
            name='type_layanan',
            field=models.CharField(choices=[('D', 'DATA'), ('P', 'PULSA')], default='P', max_length=2),
        ),
    ]
