# Generated by Django 2.0.4 on 2018-05-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0013_auto_20180516_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['operator', 'nominal', 'type_layanan']},
        ),
    ]
