# Generated by Django 2.0.4 on 2018-05-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0014_auto_20180516_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
