# Generated by Django 2.0.4 on 2018-05-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulsa', '0015_auto_20180516_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harga_sistem_update',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
