# Generated by Django 2.0.4 on 2018-05-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermember', to='userprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='limit',
            field=models.IntegerField(default=-110000),
        ),
    ]
