# Generated by Django 2.0.4 on 2018-05-02 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_profile_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembukuanTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.IntegerField(default=0)),
                ('kredit', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='agen',
            field=models.BooleanField(default=False),
        ),
    ]
