# Generated by Django 2.0.4 on 2018-05-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180527_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermember', to='userprofile.Profile'),
        ),
    ]
