# Generated by Django 2.0.4 on 2018-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180527_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.PositiveIntegerField(default=0)),
                ('kredit', models.PositiveIntegerField(default=0)),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('type_transaksi', models.PositiveSmallIntegerField(choices=[(1, 'Pembelian'), (2, 'Beli Gagal'), (3, 'Refund'), (4, 'Tambah Saldo')], default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
