# Generated by Django 2.0.4 on 2018-05-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_catatanmodal_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembukuantransaksi',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
