# Generated by Django 2.0.4 on 2018-05-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20180503_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembukuantransaksi',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.PembukuanTransaksi'),
        ),
        migrations.AddField(
            model_name='pembukuantransaksi',
            name='seq',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
