# Generated by Django 2.0.4 on 2018-06-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_pembukuantransaksi_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name']},
        ),
    ]
