# Generated by Django 2.0.4 on 2018-05-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20180505_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='limit',
            field=models.IntegerField(default=-50000),
        ),
    ]
