# Generated by Django 2.0.4 on 2018-06-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180601_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='catatanmodal',
            name='biller',
            field=models.CharField(choices=[('SB', 'Siap Bayar'), ('RB', 'Raja Biller')], default='RB', max_length=2),
        ),
    ]
