# Generated by Django 2.0.4 on 2018-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
