# Generated by Django 2.0.4 on 2018-06-30 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0011_payroll_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.PositiveIntegerField(default=1000)),
                ('method_payment', models.CharField(choices=[('MN', 'MANUAL PAYMENT'), ('VA', 'VIRTUAL ACCOUNT'), ('TR', 'TRANSFER')], max_length=2)),
                ('berita_acara', models.CharField(blank=True, max_length=200)),
                ('setor_payment', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agen', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
