# Generated by Django 2.0.4 on 2018-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20180630_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
