# Generated by Django 2.0.4 on 2018-07-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20180701_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldMarking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.PembukuanTransaksi')),
            ],
        ),
    ]
