# Generated by Django 2.0.4 on 2018-07-30 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20180729_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
