# Generated by Django 2.0.4 on 2018-07-03 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0014_auto_20180701_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('biller', models.CharField(choices=[('SB', 'Siap Bayar'), ('RB', 'Raja Biller')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nama_game', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_internal', models.CharField(blank=True, max_length=10)),
                ('nominal', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('parse_text', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('biller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='egame.Biller')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egame.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTransaksiRb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.CharField(blank=True, max_length=40)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('sn', models.CharField(blank=True, max_length=100)),
                ('ref1', models.CharField(blank=True, max_length=30)),
                ('ref2', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('ket', models.CharField(blank=True, max_length=100)),
                ('saldo_terpotong', models.PositiveIntegerField(default=0)),
                ('sisa_saldo', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiRb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_code', models.CharField(blank=True, max_length=16)),
                ('price', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Success'), (1, 'Pending'), (9, 'Gagal')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('catatan_modal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eegame_rbcctt_modal', to='userprofile.CatatanModal')),
                ('pembukuan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egame_rbbuku_transaksi', to='userprofile.PembukuanTransaksi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egame.Product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='egame_rbuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='responsetransaksirb',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='egame.TransaksiRb'),
        ),
    ]
