# Generated by Django 2.0.4 on 2018-07-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egame', '0003_auto_20180704_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['nama_game']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['developer', 'nominal']},
        ),
    ]
