# Generated by Django 2.0.4 on 2018-05-07 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etransport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='pembukuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bukutrans', to='userprofile.PembukuanTransaksi'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usertrans', to=settings.AUTH_USER_MODEL),
        ),
    ]
