# Generated by Django 2.0.4 on 2018-05-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_catatanmodal'),
        ('etransport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='catatan_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctt_trans', to='userprofile.CatatanModal'),
        ),
    ]
