# Generated by Django 2.0.4 on 2018-06-18 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etransport', '0002_transaksi_catatan_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='pembukuan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bukutrans', to='userprofile.PembukuanTransaksi'),
        ),
    ]
