# Generated by Django 2.0.4 on 2018-05-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etransport', '0002_auto_20180507_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
