# Generated by Django 2.0.4 on 2018-07-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etransport', '0003_auto_20180618_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('biller', models.CharField(choices=[('SB', 'Siap Bayar'), ('RB', 'Raja Biller')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='biller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etransport.Biller'),
        ),
    ]
