# Generated by Django 2.0.4 on 2018-05-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etransport', '0003_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parse_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
