# Generated by Django 2.0.4 on 2018-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etransport', '0005_product_harga_sistem_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='harga_sistem_update',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_beli',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
